### YamlMime:ManagedReference
items:
- uid: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  commentId: T:Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  id: SocketSettings.SocketProtocol
  parent: Bonsai.ZeroMQ
  children:
  - Bonsai.ZeroMQ.SocketSettings.SocketProtocol.InProc
  - Bonsai.ZeroMQ.SocketSettings.SocketProtocol.PGM
  - Bonsai.ZeroMQ.SocketSettings.SocketProtocol.TCP
  langs:
  - csharp
  - vb
  name: SocketSettings.SocketProtocol
  nameWithType: SocketSettings.SocketProtocol
  fullName: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  type: Enum
  source:
    remote:
      path: src/Bonsai.ZeroMQ/SocketSettings.cs
      branch: issue-1-docs
      repo: https://github.com/RoboDoig/Bonsai.ZeroMQ.git
    id: SocketProtocol
    path: ../src/Bonsai.ZeroMQ/SocketSettings.cs
    startLine: 31
  assemblies:
  - Bonsai.ZeroMQ
  namespace: Bonsai.ZeroMQ
  summary: "\nSpecifies the network protocol to be used by a socket.\n"
  example: []
  syntax:
    content: public enum SocketProtocol
    content.vb: Public Enum SocketProtocol
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.TCP
  commentId: F:Bonsai.ZeroMQ.SocketSettings.SocketProtocol.TCP
  id: TCP
  parent: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  langs:
  - csharp
  - vb
  name: TCP
  nameWithType: SocketSettings.SocketProtocol.TCP
  fullName: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.TCP
  type: Field
  source:
    remote:
      path: src/Bonsai.ZeroMQ/SocketSettings.cs
      branch: issue-1-docs
      repo: https://github.com/RoboDoig/Bonsai.ZeroMQ.git
    id: TCP
    path: ../src/Bonsai.ZeroMQ/SocketSettings.cs
    startLine: 35
  assemblies:
  - Bonsai.ZeroMQ
  namespace: Bonsai.ZeroMQ
  summary: "\nSpecifies the socket will use Transmission Control protocol.\n"
  example: []
  syntax:
    content: TCP = 0
    return:
      type: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.InProc
  commentId: F:Bonsai.ZeroMQ.SocketSettings.SocketProtocol.InProc
  id: InProc
  parent: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  langs:
  - csharp
  - vb
  name: InProc
  nameWithType: SocketSettings.SocketProtocol.InProc
  fullName: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.InProc
  type: Field
  source:
    remote:
      path: src/Bonsai.ZeroMQ/SocketSettings.cs
      branch: issue-1-docs
      repo: https://github.com/RoboDoig/Bonsai.ZeroMQ.git
    id: InProc
    path: ../src/Bonsai.ZeroMQ/SocketSettings.cs
    startLine: 40
  assemblies:
  - Bonsai.ZeroMQ
  namespace: Bonsai.ZeroMQ
  summary: "\nSpecifies the socket will use the In-Process Transport protocol.\n"
  example: []
  syntax:
    content: InProc = 1
    return:
      type: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.PGM
  commentId: F:Bonsai.ZeroMQ.SocketSettings.SocketProtocol.PGM
  id: PGM
  parent: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  langs:
  - csharp
  - vb
  name: PGM
  nameWithType: SocketSettings.SocketProtocol.PGM
  fullName: Bonsai.ZeroMQ.SocketSettings.SocketProtocol.PGM
  type: Field
  source:
    remote:
      path: src/Bonsai.ZeroMQ/SocketSettings.cs
      branch: issue-1-docs
      repo: https://github.com/RoboDoig/Bonsai.ZeroMQ.git
    id: PGM
    path: ../src/Bonsai.ZeroMQ/SocketSettings.cs
    startLine: 45
  assemblies:
  - Bonsai.ZeroMQ
  namespace: Bonsai.ZeroMQ
  summary: "\nSpecifies the socket will use the Pragmatic General Multicast protocol.\n"
  example: []
  syntax:
    content: PGM = 2
    return:
      type: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Bonsai.ZeroMQ
  commentId: N:Bonsai.ZeroMQ
  name: Bonsai.ZeroMQ
  nameWithType: Bonsai.ZeroMQ
  fullName: Bonsai.ZeroMQ
- uid: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  commentId: T:Bonsai.ZeroMQ.SocketSettings.SocketProtocol
  parent: Bonsai.ZeroMQ
  name: SocketSettings.SocketProtocol
  nameWithType: SocketSettings.SocketProtocol
  fullName: Bonsai.ZeroMQ.SocketSettings.SocketProtocol
